### ISSUE TITLE
[Feature] Ignore overridden method declaration

### ISSUE THREAD

**Issue by bivashy** [bivashy/ProximateConfigurate#10]
**Is your feature request related to a problem? Please describe.**
Currently, there is no clear way to override a method by declaring the `@Override' annotation.
For example:
```java
    @ConfigInterface
    public interface UserConfig extends User {

        @Override
        @Transient
        default String metadata(int index) {
            return metadata().get(index);
        }

    }
    
    public interface User {

        List<String> metadata();

        String metadata(int index);

    }
```
And if we will try to create `UserConfig` from valid configuration, we will see the exception (_see additional context_)

**Describe the solution you'd like**
When we will collect methods from class, we should avoid duplicate methods: overridden and their declaration. We could achieve this by including only overridden methods.

**Describe alternatives you've considered**
Currently none.

**Additional context**
```java
Exception in thread "main" java.lang.RuntimeException: org.spongepowered.configurate.serialize.SerializationException: [] of type com.bivashy.test.configurate.ProximateConfigurateTestInheritance$User: Interface methods should not have parameters: 'public abstract java.lang.String com.bivashy.test.configurate.ProximateConfigurateTestInheritance$User.test(int)'
	at com.bivashy.configurate.objectmapping.common.InterfaceMethodDiscoverer.lambda$shouldBeIgnored$6(InterfaceMethodDiscoverer.java:105)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at com.bivashy.configurate.objectmapping.common.InterfaceMethodDiscoverer.shouldBeIgnored(InterfaceMethodDiscoverer.java:101)
	at com.bivashy.configurate.objectmapping.common.InterfaceMethodDiscoverer.collectMethods(InterfaceMethodDiscoverer.java:83)
	at com.bivashy.configurate.objectmapping.common.InterfaceMethodDiscoverer.discover(InterfaceMethodDiscoverer.java:73)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.newMapper(ObjectMapperFactoryImpl.java:131)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.computeMapper(ObjectMapperFactoryImpl.java:120)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.lambda$computeFromMap$5(ObjectMapperFactoryImpl.java:290)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.computeFromMap(ObjectMapperFactoryImpl.java:288)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.get(ObjectMapperFactoryImpl.java:109)
	at com.bivashy.configurate.objectmapping.common.InterfaceObjectMapperFactory.get(InterfaceObjectMapperFactory.java:65)
	at com.bivashy.configurate.objectmapping.common.InterfaceObjectMapperFactory.deserialize(InterfaceObjectMapperFactory.java:76)
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151)
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:433)
Caused by: org.spongepowered.configurate.serialize.SerializationException: [] of type com.bivashy.test.configurate.ProximateConfigurateTestInheritance$User: Interface methods should not have parameters: 'public abstract java.lang.String com.bivashy.test.configurate.ProximateConfigurateTestInheritance$User.test(int)'
	at com.bivashy.configurate.objectmapping.common.InterfaceMethodDiscoverer.lambda$defaultBuilder$3(InterfaceMethodDiscoverer.java:53)
	at com.bivashy.configurate.objectmapping.common.InterfaceMethodDiscoverer.lambda$shouldBeIgnored$6(InterfaceMethodDiscoverer.java:103)
	... 24 more
```

**Comment by bivashy** [comment]
Easiest solution:
```java
    private static void collectMethods(AnnotatedType type, List<MethodAdapter> registeredMethods) {
        for (Method method : GenericTypeReflector.erase(type.getType()).getDeclaredMethods()) {
            MethodAdapter adapter = new MethodAdapter(method);
            if (registeredMethods.contains(adapter))
                continue;
            // Do magic
            registeredMethods.add(adapter);
        }
    }
```

MethodAdapter:
```java
    private static class MethodAdapter {

        private final String name;
        private final Class<?> returnType;
        private final Class<?>[] parameterTypes;

        public MethodAdapter(Method method) {
            this.name = method.getName();
            this.returnType = method.getReturnType();
            this.parameterTypes = method.getParameterTypes();
        }

        @Override
        public boolean equals(Object object) {
            if (this == object)
                return true;
            if (!(object instanceof MethodAdapter))
                return false;
            MethodAdapter adapter = (MethodAdapter) object;
            return Objects.equals(name, adapter.name) && Objects.equals(returnType, adapter.returnType) &&
                    Objects.deepEquals(parameterTypes, adapter.parameterTypes);
        }

        @Override
        public int hashCode() {
            return Objects.hash(name, returnType, Arrays.hashCode(parameterTypes));
        }

    }
```

But we need to think about edge-cases

**Comment by bivashy** [comment]
> But we need to think about edge-cases

```java
interface Producer<T> {
    T produce(int index);
}
```

```java
interface ConfigurationProducer implements Producer<String> {
    @Override
    @Transient
    default String produce(int index) {
        // TODO: implementation
    }
}
```

Producer#produce != ConfigurationProducer#produce

---

Update:
Solution is simple, use geantyref
```java
    private static class MethodAdapter {

        private final String name;
        private final Type returnType;
        private final Type[] parameterTypes;

        public MethodAdapter(Method method, Type declaringType) {
            this.name = method.getName();
            this.returnType = GenericTypeReflector.getReturnType(method, declaringType);
            this.parameterTypes = GenericTypeReflector.getParameterTypes(method, declaringType);
        }

        @Override
        public boolean equals(Object object) {
            if (this == object)
                return true;
            if (!(object instanceof MethodAdapter))
                return false;
            MethodAdapter adapter = (MethodAdapter) object;
            return Objects.equals(name, adapter.name) && Objects.equals(returnType, adapter.returnType) &&
                    Objects.deepEquals(parameterTypes, adapter.parameterTypes);
        }

        @Override
        public int hashCode() {
            return Objects.hash(name, returnType, Arrays.hashCode(parameterTypes));
        }

    }
```
